---
- name: Include dynamic variables 
  hosts: all
  tasks:
- import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: webserver configurations
  hosts: uat-webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml


- name: Database configurations
  hosts: db
- name: Database assignment
  import_playbook: ../static-assignments/db.yml

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 


