- hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - { role: nginx, when: enable_nginx_lb and load_balancer_is_required }
    - { role: apache, when: enable_apache_lb and load_balancer_is_required }
